### ISSUE TITLE
Kernel dll

### ISSUE THREAD

**Issue by amfaizal** [allewwaly/new-drakvuf#1]
Dear sir..
May i know how to capture system call from kernel.dll file...my drakvuf only report system call from nt..
Hope you can assist me...
Tq

**Comment by allewwaly** [comment]
you can refer to my paper "SPEMS: A Stealthy and Practical Execution Monitoring System Based on VMI" for details.

**Comment by amfaizal** [comment]
Ok ...tq

**Comment by amfaizal** [comment]
Hai...is it the new drakvuf already support the kernel.dll system call. May
i know the command to run or filter it..hope u can help me
Tq

**Comment by allewwaly** [comment]
See readme file for usage.
you can filter kernel32.dll function call by using grep.
eg. ./drakvuf -d rekall-profile domid pid | grep kernel32

**Comment by allewwaly** [comment]
An example output would be:
```
        New memory event trap set on page 114395
        Trap added @ VA 0x75e682f1 PA 0x1bedb2f1 Page 114395 for kernel32.dll!W$
RemoveDirectoryW is going to be trapped
        New memory event trap set on page 113351
        Trap added @ VA 0x75e55877 PA 0x1bac7877 Page 113351 for kernel32.dll!R$
FindFirstFileExA is going to be trapped
        New memory event trap set on page 114526
        Trap added @ VA 0x75ed4ded PA 0x1bf5eded Page 114526 for kernel32.dll!F$
GetSystemTime is going to be trapped
        New memory event trap set on page 101763
        Trap added @ VA 0x75e220f9 PA 0x18d830f9 Page 101763 for kernel32.dll!G$
GetLocalTime is going to be trapped
        New memory event trap set on page 114077
        Trap added @ VA 0x75e6a903 PA 0x1bd9d903 Page 114077 for kernel32.dll!G$
CopyFileA is going to be trapped
        New memory event trap set on page 106541
        Trap added @ VA 0x75e8532c PA 0x1a02d32c Page 106541 for kernel32.dll!C$
IsDebuggerPresent is going to be trapped
```

**Comment by amfaizal** [comment]
Ok sir...
Will try it...tq

**Comment by amfaizal** [comment]
Dear sir ..
I have tried it but cannot capture any kernel32
Here are my command
xl list
Name                                        ID   Mem VCPUs    State
Time(s)
Domain-0                                     0  8191     4     r-----
682.7
windows7-sp1                                 1  3000     2     -b----
82.4

Then i run this command

./drakvuf -d 1 -r /root/windows7-sp1.rekall.json | grep kernel32
DRAKVUF v0.5-c2da05b
Socketmon plugin requires the Rekall profile for tcpip.sys!


After this there are no output appear..

Could you please help me

tq

**Comment by allewwaly** [comment]
you should generate you own rekall profile for tcpip.sys, please carefully read readme file before you try!

> the user-level dlls' rekall profile is manufactually generated and merged with guide at http://rekall-forensic.blogspot.com/2014/02/the-rekall-profile-repository-and.html

**Comment by amfaizal** [comment]
Hai...
I will try it...tq for your help...
